In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import os
import pandas_datareader as dr
plt.style.use('seaborn-darkgrid')
import plotly.graph_objects as go
import plotly.express as px

In [2]:
os.chdir(r'/Users/marike/Documents/MARIKE/DATA SCIENCE/Final project/Marike FP/Data')

In [3]:
"""indicate in below code line (convert comment to code) the location of Speed Dating Data 
in case of checking the project from another computer"""
# os.chdir("..")

cities_path = r'WB_city_level_data_0_0.csv'
cities_df = pd.read_csv(cities_path, thousands = ',')

## 1. DATA CLEANING

### 1.1 CITIES DATASET

In [4]:
cities_df.head()

,iso3c,region_id,country_name,income_id,city_name,additional_data_annual_budget_for_waste_management_year,additional_data_annual_solid_waste_budget_year,additional_data_annual_swm_budget_2017_year,additional_data_annual_swm_budget_year,additional_data_annual_waste_budget_year,...,waste_treatment_compost_percent,waste_treatment_controlled_landfill_percent,waste_treatment_incineration_percent,waste_treatment_landfill_unspecified_percent,waste_treatment_open_dump_percent,waste_treatment_other_percent,waste_treatment_recycling_percent,waste_treatment_sanitary_landfill_landfill_gas_system_percent,waste_treatment_unaccounted_for_percent,waste_treatment_waterways_marine_percent
0,AFG,SAS,Afghanistan,LIC,Jalalabad,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
1,AFG,SAS,Afghanistan,LIC,Kandahar,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
2,AFG,SAS,Afghanistan,LIC,Mazar-E-Sharif,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN
3,AFG,SAS,Afghanistan,LIC,Kabul,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,75.0,NaN,NaN,NaN,25.0,NaN
4,AFG,SAS,Afghanistan,LIC,HiratÂ,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN

In [5]:
#we check whether dataset has some duplicated row:
print('Cities dataset has ', cities_df.duplicated().sum(),' duplicated rows.')

Cities dataset has  0  duplicated rows.

In [6]:
cities_df.shape

(367, 113)

In [7]:
cities_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Columns: 113 entries, iso3c to waste_treatment_waterways_marine_percent
dtypes: float64(72), object(41)
memory usage: 324.1+ KB

According to dataset information, it is composed of 113 variables, 72 are numerical variables and 41 seem to be categorical variables. As we have to many variables for the information to be displayed, we print the details of all variables.

In [8]:
for col in cities_df.columns: 
    print(col,' , ',cities_df[col].dtypes,', null values:', cities_df[col].isna().sum())

iso3c  ,  object , null values: 0
region_id  ,  object , null values: 0
country_name  ,  object , null values: 0
income_id  ,  object , null values: 0
city_name  ,  object , null values: 0
additional_data_annual_budget_for_waste_management_year  ,  object , null values: 366
additional_data_annual_solid_waste_budget_year  ,  object , null values: 366
additional_data_annual_swm_budget_2017_year  ,  float64 , null values: 366
additional_data_annual_swm_budget_year  ,  float64 , null values: 365
additional_data_annual_waste_budget_year  ,  float64 , null values: 366
additional_data_collection_ton  ,  float64 , null values: 366
additional_data_number_of_scavengers_on_dumpsites_number  ,  float64 , null values: 366
additional_data_other_user_fees_na  ,  object , null values: 366
additional_data_swm_contract_arrangement_1_year_contract_period  ,  object , null values: 366
additional_data_swm_contract_arrangement_3_year_contract_period  ,  object , null values: 366
additional_data_total_annual_costs_to_collect_and_dispose_of_city_s_waste_year  ,  float64 , null values: 366
additional_data_total_swm_expenditures_year  ,  float64 , null values: 366
additional_data_total_waste_management_budget_year  ,  float64 , null values: 366
communication_list_of_channels_through_which_the_city_collects_feedback_from_it_residents_on_issues_related_to_solid_waste_services_na  ,  object , null values: 361
communication_summary_of_key_solid_waste_information_made_periodically_available_to_the_public_na  ,  object , null values: 341
composition_food_organic_waste_percent  ,  float64 , null values: 76
composition_glass_percent  ,  float64 , null values: 98
composition_metal_percent  ,  float64 , null values: 102
composition_other_percent  ,  float64 , null values: 77
composition_paper_cardboard_percent  ,  float64 , null values: 77
composition_plastic_percent  ,  float64 , null values: 84
composition_rubber_leather_percent  ,  float64 , null values: 259
composition_wood_percent  ,  float64 , null values: 269
composition_yard_garden_green_waste_percent  ,  float64 , null values: 271
informal_sector_child_waste_pickers_number  ,  float64 , null values: 361
informal_sector_child_waste_pickers_percent  ,  float64 , null values: 362
informal_sector_female_waste_pickers_number  ,  float64 , null values: 364
informal_sector_female_waste_pickers_percent  ,  float64 , null values: 361
informal_sector_social_safeguards_for_waste_pickers_list  ,  object , null values: 363
informal_sector_total_waste_pickers_number  ,  float64 , null values: 364
institutional_framework_department_dedicated_to_solid_waste_management_na  ,  object , null values: 129
institutional_framework_environmental_assessment_for_solid_waste_management_in_the_past_5_years_na  ,  object , null values: 265
institutional_framework_information_system_for_solid_waste_management_na  ,  object , null values: 228
institutional_framework_performed_a_social_assessment_for_solid_waste_management_in_the_past_5_years_na  ,  object , null values: 268
institutional_framework_unit_enforcing_solid_waste_issues_in_the_city_such_as_illegal_dumping_or_littering_na  ,  object , null values: 241
legal_framework_long_term_integrated_solid_waste_master_plan_na  ,  object , null values: 179
legal_framework_master_plan_is_being_implemented_na  ,  object , null values: 251
legal_framework_solid_waste_management_rules_and_regulations_na  ,  object , null values: 127
n_waste_pickers_number_of_waste_pickers_number_of_people  ,  float64 , null values: 270
percent_informal_sector_percent_collected_by_informal_sector_percent  ,  float64 , null values: 308
population_population_number_of_people  ,  float64 , null values: 10
primary_collection_mode_form_of_primary_collection_na  ,  object , null values: 126
separation_breakdonw_cans_and_metals_na  ,  object , null values: 217
separation_breakdonw_glass_na  ,  object , null values: 215
separation_breakdonw_organics_na  ,  object , null values: 226
separation_breakdonw_other_na  ,  object , null values: 307
separation_breakdonw_paper_cardboard_na  ,  object , null values: 212
separation_breakdonw_plastics_and_packaging_na  ,  object , null values: 213
separation_existence_of_source_separation_na  ,  object , null values: 175
subisidies_other_subsidies_or_transfers_na  ,  float64 , null values: 359
subisidies_subsidies_or_transfers_from_a_central_government_authority_na  ,  float64 , null values: 343
total_msw_total_msw_generated_tons_year  ,  float64 , null values: 41
transportation_distance_from_city_center_to_main_landfill_or_dumpsite_km  ,  float64 , null values: 237
transportation_distance_km  ,  float64 , null values: 366
transportation_distance_km_year  ,  float64 , null values: 342
transportation_distance_na  ,  object , null values: 366
transportation_distance_total_km_day  ,  float64 , null values: 366
transportation_scale_calibration_and_operation_status_na  ,  object , null values: 290
transportation_scale_usage_na  ,  object , null values: 267
transportation_transfer_station_or_collection_point_aggregation_na  ,  object , null values: 238
transportation_transfer_station_or_colletion_point_aggregation_na  ,  object , null values: 366
transportation_transfer_stations_needed_number  ,  float64 , null values: 338
transportation_transfer_stations_needed_na  ,  object , null values: 348
transportation_transfer_stations_operational_number  ,  float64 , null values: 287
transportation_transfer_stations_operational_na  ,  float64 , null values: 343
transportation_trips_per_year_na  ,  float64 , null values: 363
transportation_trips_per_year_trips_year  ,  float64 , null values: 301
waste_collection_cost_recovery_commercial_fee_amount_na  ,  object , null values: 288
waste_collection_cost_recovery_household_fee_amount_na  ,  object , null values: 221
waste_collection_cost_recovery_household_fee_to_private_agents_non_municipal_na  ,  float64 , null values: 365
waste_collection_cost_recovery_metadata_commercial_fee_type_na  ,  object , null values: 283
waste_collection_cost_recovery_metadata_household_fee_type_na  ,  object , null values: 217
waste_collection_cost_recovery_metadata_main_method_of_household_billing_na  ,  object , null values: 294
waste_collection_cost_recovery_total_collection_revenues_na  ,  float64 , null values: 308
waste_collection_cost_recovery_total_commercial_fees_collected_na  ,  float64 , null values: 349
waste_collection_cost_recovery_total_household_fees_collected_na  ,  float64 , null values: 339
waste_collection_coverage_total_percent_of_geographic_area_percent_of_geographic_area  ,  float64 , null values: 353
waste_collection_coverage_total_percent_of_households_percent_of_households  ,  float64 , null values: 327
waste_collection_coverage_total_percent_of_population_percent_of_population  ,  float64 , null values: 290
waste_collection_coverage_total_percent_of_waste_percent_of_waste  ,  float64 , null values: 204
waste_disposal_cost_recovery_metadata_disposal_fee_type_na  ,  object , null values: 319
waste_disposal_cost_recovery_other_revenues_na  ,  float64 , null values: 344
waste_disposal_cost_recovery_per_unit_disposal_cost_na  ,  float64 , null values: 279
waste_disposal_cost_recovery_total_disposal_revenues_na  ,  float64 , null values: 343
waste_disposal_cost_recovery_total_revenues_from_compost_na  ,  float64 , null values: 362
waste_disposal_cost_recovery_total_revenues_from_recycling_na  ,  float64 , null values: 354
waste_management_cost_controlled_landfill_na  ,  float64 , null values: 354
waste_management_cost_incineration_na  ,  float64 , null values: 360
waste_management_cost_open_dump_na  ,  float64 , null values: 355
waste_management_cost_other_na  ,  float64 , null values: 321
waste_management_cost_recycling_na  ,  float64 , null values: 363
waste_management_cost_sanitary_landfill_landfill_gas_system_na  ,  float64 , null values: 356
waste_to_energy_cost_recovery_amount_of_energy_distributed_through_feed_in_tariff_kwh_year  ,  float64 , null values: 358
waste_to_energy_cost_recovery_amount_of_energy_generated_kwh_year  ,  float64 , null values: 347
waste_to_energy_cost_recovery_feed_in_tariff_amount_na  ,  float64 , null values: 361
waste_to_energy_cost_recovery_total_revenues_from_energy_recovery_na  ,  float64 , null values: 357
waste_treatment_advanced_thermal_treatment_percent  ,  float64 , null values: 365
waste_treatment_anaerobic_digestion_percent  ,  float64 , null values: 355
waste_treatment_compost_percent  ,  float64 , null values: 300
waste_treatment_controlled_landfill_percent  ,  float64 , null values: 307
waste_treatment_incineration_percent  ,  float64 , null values: 338
waste_treatment_landfill_unspecified_percent  ,  float64 , null values: 351
waste_treatment_open_dump_percent  ,  float64 , null values: 267
waste_treatment_other_percent  ,  float64 , null values: 319
waste_treatment_recycling_percent  ,  float64 , null values: 239
waste_treatment_sanitary_landfill_landfill_gas_system_percent  ,  float64 , null values: 311
waste_treatment_unaccounted_for_percent  ,  float64 , null values: 246
waste_treatment_waterways_marine_percent  ,  float64 , null values: 363

Our dataset has a length of 367 rows that correspond to cities but from the information, we see that information is missing for many variables. We check the extension of this fact.

In [9]:
#We import functions we have created to use repeated times in this project.
from MC_FP_UsefulFunctions import *

In [10]:
#we use function "show_null" to display characteristics of missing information in dataframe.

cities_null_perc = show_null(cities_df)
cities_null_perc

,Null data amount,Missing data (%),type
additional_data_annual_budget_for_waste_management_year,366,99.72752,object
additional_data_swm_contract_arrangement_3_year_contract_period,366,99.72752,object
additional_data_annual_solid_waste_budget_year,366,99.72752,object
transportation_distance_km,366,99.72752,float64
transportation_distance_na,366,99.72752,object
...,...,...,...
city_name,0,0.00000,object
income_id,0,0.00000,object
region_id,0,0.00000,object
iso3c,0,0.00000,object
country_name,0,0.00000,object

Some variables have almost a 100% of missing information. When the variable has o much missing information, we disregard it because it cannot give representative information. We chech the extension of the issue in our dataset:

In [11]:
print('Number of variables with more than 90% missing information: ', len(cities_null_perc.loc[cities_null_perc['Missing data (%)']>90]), '. That is to say ',round(len(cities_null_perc.loc[cities_null_perc['Missing data (%)']>90])*100/len(cities_null_perc),2),'% of the variables')
print('Number of variables with more than 75% missing information: ', len(cities_null_perc.loc[cities_null_perc['Missing data (%)']>75]), '. That is to say ',round(len(cities_null_perc.loc[cities_null_perc['Missing data (%)']>75])*100/len(cities_null_perc),2),'% of the variables')
print('Number of variables with more than 50% missing information: ', len(cities_null_perc.loc[cities_null_perc['Missing data (%)']>50]), '. That is to say ',round(len(cities_null_perc.loc[cities_null_perc['Missing data (%)']>50])*100/len(cities_null_perc),2),'% of the variables')
print('Number of variables with more than 40% missing information: ', len(cities_null_perc.loc[cities_null_perc['Missing data (%)']>40]), '. That is to say ',round(len(cities_null_perc.loc[cities_null_perc['Missing data (%)']>40])*100/len(cities_null_perc),2),'% of the variables')

Number of variables with more than 90% missing information:  54 . That is to say  47.79 % of the variables
Number of variables with more than 75% missing information:  72 . That is to say  63.72 % of the variables
Number of variables with more than 50% missing information:  95 . That is to say  84.07 % of the variables
Number of variables with more than 40% missing information:  97 . That is to say  85.84 % of the variables

Among variables without missing information, there are at least two that we consider important to look at more detailly: the *region_id* and the *income_id* because we know that waste issue is dealt with on different way according to continents and above all economical situation so before dropping massively information, we will check if the missing information is so important for each sub geographical or economic area.

In [12]:
cities_df.region_id.unique()

array(['SAS', 'SSF', 'ECS', 'MEA', 'LCN', 'EAS', 'NAC'], dtype=object)

**Meaning of regions codes:**

***EAS*: East Asia & Pacific**

***ECS*: Europe & Central Asia**

***LCN*: Latin America & Caribbean**

***MEA*: Middle East & North Africa**

***NAC*: North America**

***SAS*: South Asia**

***SSF*: Sub-Saharan Africa**

In [13]:
cities_df.income_id.unique()

array(['LIC', 'LMC', 'UMC', 'HIC'], dtype=object)

**Meaning of income codes:**

***HIC*: High Income Country**

***UMC*: Upper & Middle Income Country**

***LMC*: Lower & Middle Income Country**

***LIC*: Low Income Country**

In [14]:
cities_df.replace({'LIC': 'LowIncome', 'LMC': 'LowMiddleIncome','UMC':'MiddleUpperIncome','HIC':'HighIncome'},inplace=True)

In [15]:
Cities_null_perc_X_region_income = pd.DataFrame()
Cities_null_perc_X_region_income['World']=cities_null_perc['Missing data (%)']

for x in cities_df.region_id.unique():
    null_perc_city_region = show_null(cities_df.loc[cities_df.region_id == x])
    Cities_null_perc_X_region_income[x]=round(null_perc_city_region['Missing data (%)'],2)
    
for x in cities_df.income_id.unique():
    null_perc_city_income = show_null(cities_df.loc[cities_df.income_id == x])
    Cities_null_perc_X_region_income[x]=round(null_perc_city_income['Missing data (%)'],2)

Cities_null_perc_X_region_income

,World,SAS,SSF,ECS,MEA,LCN,EAS,NAC,LowIncome,LowMiddleIncome,MiddleUpperIncome,HighIncome
additional_data_annual_budget_for_waste_management_year,99.72752,100.0,100.0,100.0,100.0,100.0,97.5,100.0,100.00,99.19,100.00,100.00
additional_data_swm_contract_arrangement_3_year_contract_period,99.72752,100.0,100.0,100.0,100.0,100.0,97.5,100.0,100.00,100.00,98.77,100.00
additional_data_annual_solid_waste_budget_year,99.72752,100.0,100.0,100.0,100.0,100.0,97.5,100.0,100.00,99.19,100.00,100.00
transportation_distance_km,99.72752,98.8,100.0,100.0,100.0,100.0,100.0,100.0,98.65,100.00,100.00,100.00
transportation_distance_na,99.72752,100.0,100.0,100.0,100.0,100.0,97.5,100.0,100.00,100.00,100.00,98.86
...,...,...,...,...,...,...,...,...,...,...,...,...
city_name,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
income_id,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
region_id,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
iso3c,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
country_name,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00

We can see that some variables have a very high percentage of missing information. **We decide to keep only variables with less than 50% of missing information except for variables with 50 to 70% missing information but for which there is a world area (defined geographically or by income) where this variable has less than 30% missing information.** 

Indeed we know that some variables will only be informed in areas where waste issue is better dealt with.

In [16]:
Notallregions_Income_HighNaNPerc=[]

for x in Cities_null_perc_X_region_income.index:
    
    if Cities_null_perc_X_region_income.at[x,'World']<70 and Cities_null_perc_X_region_income.at[x,'World']>50:
        
        for y in cities_df.region_id.unique():
            if Cities_null_perc_X_region_income.at[x,y]<30:
                Notallregions_Income_HighNaNPerc.append(x)
                
        for z in cities_df.income_id.unique():
            if Cities_null_perc_X_region_income.at[x,z]<30:
                Notallregions_Income_HighNaNPerc.append(x)
                
Notallregions_Income_HighNaNPerc

['legal_framework_master_plan_is_being_implemented_na',
 'institutional_framework_unit_enforcing_solid_waste_issues_in_the_city_such_as_illegal_dumping_or_littering_na',
 'waste_treatment_recycling_percent',
 'institutional_framework_information_system_for_solid_waste_management_na',
 'separation_breakdonw_organics_na',
 'waste_collection_cost_recovery_household_fee_amount_na',
 'separation_breakdonw_cans_and_metals_na',
 'separation_breakdonw_cans_and_metals_na',
 'separation_breakdonw_glass_na',
 'separation_breakdonw_glass_na',
 'separation_breakdonw_plastics_and_packaging_na',
 'separation_breakdonw_plastics_and_packaging_na',
 'separation_breakdonw_paper_cardboard_na',
 'separation_breakdonw_paper_cardboard_na',
 'waste_collection_coverage_total_percent_of_waste_percent_of_waste',
 'waste_collection_coverage_total_percent_of_waste_percent_of_waste']

In [17]:
Notallregions_Income_HighNaNPerc_df = pd.DataFrame({'Variable to keep':Notallregions_Income_HighNaNPerc})

In [18]:
Notallregions_Income_HighNaNPerc_df['Variable to keep'].unique()

array(['legal_framework_master_plan_is_being_implemented_na',
       'institutional_framework_unit_enforcing_solid_waste_issues_in_the_city_such_as_illegal_dumping_or_littering_na',
       'waste_treatment_recycling_percent',
       'institutional_framework_information_system_for_solid_waste_management_na',
       'separation_breakdonw_organics_na',
       'waste_collection_cost_recovery_household_fee_amount_na',
       'separation_breakdonw_cans_and_metals_na',
       'separation_breakdonw_glass_na',
       'separation_breakdonw_plastics_and_packaging_na',
       'separation_breakdonw_paper_cardboard_na',
       'waste_collection_coverage_total_percent_of_waste_percent_of_waste'],
      dtype=object)

In [19]:
ColToDrop = []
for x in Cities_null_perc_X_region_income.index:
    if Cities_null_perc_X_region_income.at[x,'World']>50:
        if x not in Notallregions_Income_HighNaNPerc_df['Variable to keep'].unique():
            ColToDrop.append(x)

ColToDrop

['additional_data_annual_budget_for_waste_management_year',
 'additional_data_swm_contract_arrangement_3_year_contract_period',
 'additional_data_annual_solid_waste_budget_year',
 'transportation_distance_km',
 'transportation_distance_na',
 'transportation_distance_total_km_day',
 'transportation_transfer_station_or_colletion_point_aggregation_na',
 'additional_data_total_swm_expenditures_year',
 'additional_data_total_annual_costs_to_collect_and_dispose_of_city_s_waste_year',
 'additional_data_total_waste_management_budget_year',
 'additional_data_swm_contract_arrangement_1_year_contract_period',
 'additional_data_other_user_fees_na',
 'additional_data_number_of_scavengers_on_dumpsites_number',
 'additional_data_collection_ton',
 'additional_data_annual_waste_budget_year',
 'additional_data_annual_swm_budget_2017_year',
 'waste_treatment_advanced_thermal_treatment_percent',
 'waste_collection_cost_recovery_household_fee_to_private_agents_non_municipal_na',
 'additional_data_annual_swm_budget_year',
 'informal_sector_female_waste_pickers_number',
 'informal_sector_total_waste_pickers_number',
 'waste_management_cost_recycling_na',
 'transportation_trips_per_year_na',
 'informal_sector_social_safeguards_for_waste_pickers_list',
 'waste_treatment_waterways_marine_percent',
 'informal_sector_child_waste_pickers_percent',
 'waste_disposal_cost_recovery_total_revenues_from_compost_na',
 'informal_sector_child_waste_pickers_number',
 'informal_sector_female_waste_pickers_percent',
 'waste_to_energy_cost_recovery_feed_in_tariff_amount_na',
 'communication_list_of_channels_through_which_the_city_collects_feedback_from_it_residents_on_issues_related_to_solid_waste_services_na',
 'waste_management_cost_incineration_na',
 'subisidies_other_subsidies_or_transfers_na',
 'waste_to_energy_cost_recovery_amount_of_energy_distributed_through_feed_in_tariff_kwh_year',
 'waste_to_energy_cost_recovery_total_revenues_from_energy_recovery_na',
 'waste_management_cost_sanitary_landfill_landfill_gas_system_na',
 'waste_management_cost_open_dump_na',
 'waste_treatment_anaerobic_digestion_percent',
 'waste_disposal_cost_recovery_total_revenues_from_recycling_na',
 'waste_management_cost_controlled_landfill_na',
 'waste_collection_coverage_total_percent_of_geographic_area_percent_of_geographic_area',
 'waste_treatment_landfill_unspecified_percent',
 'waste_collection_cost_recovery_total_commercial_fees_collected_na',
 'transportation_transfer_stations_needed_na',
 'waste_to_energy_cost_recovery_amount_of_energy_generated_kwh_year',
 'waste_disposal_cost_recovery_other_revenues_na',
 'subisidies_subsidies_or_transfers_from_a_central_government_authority_na',
 'waste_disposal_cost_recovery_total_disposal_revenues_na',
 'transportation_transfer_stations_operational_na',
 'transportation_distance_km_year',
 'communication_summary_of_key_solid_waste_information_made_periodically_available_to_the_public_na',
 'waste_collection_cost_recovery_total_household_fees_collected_na',
 'transportation_transfer_stations_needed_number',
 'waste_treatment_incineration_percent',
 'waste_collection_coverage_total_percent_of_households_percent_of_households',
 'waste_management_cost_other_na',
 'waste_treatment_other_percent',
 'waste_disposal_cost_recovery_metadata_disposal_fee_type_na',
 'waste_treatment_sanitary_landfill_landfill_gas_system_percent',
 'percent_informal_sector_percent_collected_by_informal_sector_percent',
 'waste_collection_cost_recovery_total_collection_revenues_na',
 'separation_breakdonw_other_na',
 'waste_treatment_controlled_landfill_percent',
 'transportation_trips_per_year_trips_year',
 'waste_treatment_compost_percent',
 'waste_collection_cost_recovery_metadata_main_method_of_household_billing_na',
 'transportation_scale_calibration_and_operation_status_na',
 'waste_collection_coverage_total_percent_of_population_percent_of_population',
 'waste_collection_cost_recovery_commercial_fee_amount_na',
 'transportation_transfer_stations_operational_number',
 'waste_collection_cost_recovery_metadata_commercial_fee_type_na',
 'waste_disposal_cost_recovery_per_unit_disposal_cost_na',
 'composition_yard_garden_green_waste_percent',
 'n_waste_pickers_number_of_waste_pickers_number_of_people',
 'composition_wood_percent',
 'institutional_framework_performed_a_social_assessment_for_solid_waste_management_in_the_past_5_years_na',
 'waste_treatment_open_dump_percent',
 'transportation_scale_usage_na',
 'institutional_framework_environmental_assessment_for_solid_waste_management_in_the_past_5_years_na',
 'composition_rubber_leather_percent',
 'waste_treatment_unaccounted_for_percent',
 'transportation_transfer_station_or_collection_point_aggregation_na',
 'transportation_distance_from_city_center_to_main_landfill_or_dumpsite_km',
 'waste_collection_cost_recovery_metadata_household_fee_type_na']

In [20]:
cities_df_1 = cities_df.drop(ColToDrop, axis=1)
cities_df_1

,iso3c,region_id,country_name,income_id,city_name,composition_food_organic_waste_percent,composition_glass_percent,composition_metal_percent,composition_other_percent,composition_paper_cardboard_percent,...,separation_breakdonw_cans_and_metals_na,separation_breakdonw_glass_na,separation_breakdonw_organics_na,separation_breakdonw_paper_cardboard_na,separation_breakdonw_plastics_and_packaging_na,separation_existence_of_source_separation_na,total_msw_total_msw_generated_tons_year,waste_collection_cost_recovery_household_fee_amount_na,waste_collection_coverage_total_percent_of_waste_percent_of_waste,waste_treatment_recycling_percent
0,AFG,SAS,Afghanistan,LowIncome,Jalalabad,1.0455,1.1175,0.0175,84.854,0.080,...,No,No,No,No,No,No,58914.45,NaN,NaN,NaN
1,AFG,SAS,Afghanistan,LowIncome,Kandahar,11.6000,2.3110,0.1690,64.364,1.499,...,No,No,No,No,No,No,120971.00,NaN,NaN,NaN
2,AFG,SAS,Afghanistan,LowIncome,Mazar-E-Sharif,50.5000,1.3200,0.3200,28.870,1.690,...,No,No,No,No,No,No,52368.40,NaN,NaN,NaN
3,AFG,SAS,Afghanistan,LowIncome,Kabul,13.5000,1.0000,0.5000,63.000,5.000,...,NaN,NaN,NaN,NaN,NaN,NaN,1989250.00,700,75.0,NaN
4,AFG,SAS,Afghanistan,LowIncome,HiratÂ,52.9400,1.4700,0.2300,23.050,3.670,...,No,No,No,No,No,No,91644.70,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,ZWE,SSF,Zimbabwe,LowIncome,HarareÂ,22.6100,6.4500,NaN,32.740,19.690,...,NaN,NaN,NaN,NaN,NaN,No,352334.50,NaN,NaN,NaN
363,ZWE,SSF,Zimbabwe,LowIncome,Gweru,62.4000,3.0000,3.8000,13.900,6.700,...,NaN,NaN,NaN,NaN,NaN,NaN,37887.60,NaN,NaN,NaN
364,ZWE,SSF,Zimbabwe,LowIncome,Kariba,52.0000,2.0000,3.0000,25.000,7.000,...,NaN,NaN,NaN,NaN,NaN,NaN,7423.36,NaN,NaN,NaN
365,ZWE,SSF,Zimbabwe,LowIncome,Masvingo City,15.0000,4.0000,5.0000,6.000,30.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
366,ZWE,SSF,Zimbabwe,LowIncome,SakubvaÂ,32.0000,5.0000,6.0000,7.000,27.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

***country_name* variable can be dropped because its information is repeated in *iso3c*.**

***iso3c* is country code according to United Nations (https://unstats.un.org/unsd/tradekb/knowledgebase/country-code).**

In [21]:
cities_df_2 = cities_df_1.drop(['country_name'],axis=1)
cities_df_2 = cities_df_2.rename(columns={'iso3c': 'country_code'})
cities_df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 28 columns):
country_code                                                                                                     367 non-null object
region_id                                                                                                        367 non-null object
income_id                                                                                                        367 non-null object
city_name                                                                                                        367 non-null object
composition_food_organic_waste_percent                                                                           291 non-null float64
composition_glass_percent                                                                                        269 non-null float64
composition_metal_percent                                                                                        265 non-null float64
composition_other_percent                                                                                        290 non-null float64
composition_paper_cardboard_percent                                                                              290 non-null float64
composition_plastic_percent                                                                                      283 non-null float64
institutional_framework_department_dedicated_to_solid_waste_management_na                                        238 non-null object
institutional_framework_information_system_for_solid_waste_management_na                                         139 non-null object
institutional_framework_unit_enforcing_solid_waste_issues_in_the_city_such_as_illegal_dumping_or_littering_na    126 non-null object
legal_framework_long_term_integrated_solid_waste_master_plan_na                                                  188 non-null object
legal_framework_master_plan_is_being_implemented_na                                                              116 non-null object
legal_framework_solid_waste_management_rules_and_regulations_na                                                  240 non-null object
population_population_number_of_people                                                                           357 non-null float64
primary_collection_mode_form_of_primary_collection_na                                                            241 non-null object
separation_breakdonw_cans_and_metals_na                                                                          150 non-null object
separation_breakdonw_glass_na                                                                                    152 non-null object
separation_breakdonw_organics_na                                                                                 141 non-null object
separation_breakdonw_paper_cardboard_na                                                                          155 non-null object
separation_breakdonw_plastics_and_packaging_na                                                                   154 non-null object
separation_existence_of_source_separation_na                                                                     192 non-null object
total_msw_total_msw_generated_tons_year                                                                          326 non-null float64
waste_collection_cost_recovery_household_fee_amount_na                                                           146 non-null object
waste_collection_coverage_total_percent_of_waste_percent_of_waste                                                163 non-null float64
waste_treatment_recycling_percent                                                                                128 non-null float64
dtypes: float64(10), object(18)
memory usage: 80.4+ KB

In [22]:
for x in cities_df_2.columns:
    if cities_df_2[x].dtypes==object:
        if x not in ['region_id','country_code','city_name']:
            print (x,' , ', cities_df_2[x].unique())

income_id  ,  ['LowIncome' 'LowMiddleIncome' 'MiddleUpperIncome' 'HighIncome']
institutional_framework_department_dedicated_to_solid_waste_management_na  ,  ['Yes' nan 'No']
institutional_framework_information_system_for_solid_waste_management_na  ,  ['No' nan 'Yes' 'None']
institutional_framework_unit_enforcing_solid_waste_issues_in_the_city_such_as_illegal_dumping_or_littering_na  ,  [nan 'No' 'Yes']
legal_framework_long_term_integrated_solid_waste_master_plan_na  ,  ['No' nan 'yes' 'Yes' 'None']
legal_framework_master_plan_is_being_implemented_na  ,  ['No' nan 'yes' 'Yes']
legal_framework_solid_waste_management_rules_and_regulations_na  ,  ['Yes' nan 'yes' 'No']
primary_collection_mode_form_of_primary_collection_na  ,  ['Door-to-door collection' 'Centralized drop-off point' nan
 'Curbside collection' 'Curbside' 'Multiple'
 'Door-to-door collection: waste collector knocks on door or rings doorbell and waits for resident to bring waste.'
 'Other' 'Door-to-door-collection' 'Block collection'
 'centralized and curbside' 'Door to door collection']
separation_breakdonw_cans_and_metals_na  ,  ['No' nan 'Yes']
separation_breakdonw_glass_na  ,  ['No' nan 'Yes']
separation_breakdonw_organics_na  ,  ['No' nan 'Yes']
separation_breakdonw_paper_cardboard_na  ,  ['No' nan 'Yes']
separation_breakdonw_plastics_and_packaging_na  ,  ['No' nan 'Yes']
separation_existence_of_source_separation_na  ,  ['No' nan 'Yes']
waste_collection_cost_recovery_household_fee_amount_na  ,  [nan '700' '19' '480' '150' '50' '25.65' '299' '230' '0.3' '89' '1750'
 '2750' '22.5' '40' '155' '0' '6.4000000000000001E-2' '2.7' '3.14' '2.5'
 '11.89' '11.73' '249.67' '64' '261' '3' '18301.96' '25069.57' '1000'
 '1105.04â€‹' '3131.44' '13.91' '125' '15' '100' '242' '1870' '10' '20'
 '30' '157.5' '600' '60' '2.1000000000000001E-2' '244' '225' '750' '575'
 '197.5' '29' '120' '161.16999999999999' '450' '1.87' '0.92' '3.3' '27000'
 '14.22' '12.3' '9.51' '5.0999999999999996' '33.6' '300' '3.59' '3.6'
 '2250' '45' '1150' '280' '212.66' '2.21' '2.8' '52' '0.17' '1.83' '21.2'
 '5.4' '5.9' '5.48' '5.03' '2.5299999999999998' '1500' '500'
 '4.2699999999999996' '94.75' '2504.25' '187.36' '11166.66' '1' '4.3'
 '22.85' '3500' '0.5' '7500' '5' '4.6500000000000004' '18.8']

***waste_collection_cost_recovery_household_fee_amount_na* variable should be recognized as numerical value but we do not have information about considered currency and values are very disparate, so we will also drop this variable.**

In [23]:
cities_df_3 = cities_df_2.drop(['waste_collection_cost_recovery_household_fee_amount_na'], axis=1)

#### We notice that among the categorical variables, some have binary variables with NO or YES values but in some cases null information is considered instaed of NO or the variables have unappropriate repeated values because of lower or upper case writing. We correct this:

In [24]:
cities_df_3.replace({'Yes':'yes','No':'no','None':'no'},inplace=True)

In [25]:
VariableReplaceNanbyNo = []
for x in cities_df_3.columns:
    if cities_df_3[x].dtypes==object:
        if 'yes' in cities_df_3[x].unique():
            VariableReplaceNanbyNo.append(x)

VariableReplaceNanbyNo

['institutional_framework_department_dedicated_to_solid_waste_management_na',
 'institutional_framework_information_system_for_solid_waste_management_na',
 'institutional_framework_unit_enforcing_solid_waste_issues_in_the_city_such_as_illegal_dumping_or_littering_na',
 'legal_framework_long_term_integrated_solid_waste_master_plan_na',
 'legal_framework_master_plan_is_being_implemented_na',
 'legal_framework_solid_waste_management_rules_and_regulations_na',
 'separation_breakdonw_cans_and_metals_na',
 'separation_breakdonw_glass_na',
 'separation_breakdonw_organics_na',
 'separation_breakdonw_paper_cardboard_na',
 'separation_breakdonw_plastics_and_packaging_na',
 'separation_existence_of_source_separation_na']

In [26]:
for x in VariableReplaceNanbyNo:
    cities_df_3[x].fillna('no', inplace=True)

cities_df_3.isna().sum()

country_code                                                                                                       0
region_id                                                                                                          0
income_id                                                                                                          0
city_name                                                                                                          0
composition_food_organic_waste_percent                                                                            76
composition_glass_percent                                                                                         98
composition_metal_percent                                                                                        102
composition_other_percent                                                                                         77
composition_paper_cardboard_percent                                                                               77
composition_plastic_percent                                                                                       84
institutional_framework_department_dedicated_to_solid_waste_management_na                                          0
institutional_framework_information_system_for_solid_waste_management_na                                           0
institutional_framework_unit_enforcing_solid_waste_issues_in_the_city_such_as_illegal_dumping_or_littering_na      0
legal_framework_long_term_integrated_solid_waste_master_plan_na                                                    0
legal_framework_master_plan_is_being_implemented_na                                                                0
legal_framework_solid_waste_management_rules_and_regulations_na                                                    0
population_population_number_of_people                                                                            10
primary_collection_mode_form_of_primary_collection_na                                                            126
separation_breakdonw_cans_and_metals_na                                                                            0
separation_breakdonw_glass_na                                                                                      0
separation_breakdonw_organics_na                                                                                   0
separation_breakdonw_paper_cardboard_na                                                                            0
separation_breakdonw_plastics_and_packaging_na                                                                     0
separation_existence_of_source_separation_na                                                                       0
total_msw_total_msw_generated_tons_year                                                                           41
waste_collection_coverage_total_percent_of_waste_percent_of_waste                                                204
waste_treatment_recycling_percent                                                                                239
dtype: int64

In [27]:
for x in cities_df_3.columns:
    if cities_df_3[x].dtypes==object:
        if x not in ['region_id','country_code','city_name']:
            print (x,' , ', cities_df_3[x].unique())

income_id  ,  ['LowIncome' 'LowMiddleIncome' 'MiddleUpperIncome' 'HighIncome']
institutional_framework_department_dedicated_to_solid_waste_management_na  ,  ['yes' 'no']
institutional_framework_information_system_for_solid_waste_management_na  ,  ['no' 'yes']
institutional_framework_unit_enforcing_solid_waste_issues_in_the_city_such_as_illegal_dumping_or_littering_na  ,  ['no' 'yes']
legal_framework_long_term_integrated_solid_waste_master_plan_na  ,  ['no' 'yes']
legal_framework_master_plan_is_being_implemented_na  ,  ['no' 'yes']
legal_framework_solid_waste_management_rules_and_regulations_na  ,  ['yes' 'no']
primary_collection_mode_form_of_primary_collection_na  ,  ['Door-to-door collection' 'Centralized drop-off point' nan
 'Curbside collection' 'Curbside' 'Multiple'
 'Door-to-door collection: waste collector knocks on door or rings doorbell and waits for resident to bring waste.'
 'Other' 'Door-to-door-collection' 'Block collection'
 'centralized and curbside' 'Door to door collection']
separation_breakdonw_cans_and_metals_na  ,  ['no' 'yes']
separation_breakdonw_glass_na  ,  ['no' 'yes']
separation_breakdonw_organics_na  ,  ['no' 'yes']
separation_breakdonw_paper_cardboard_na  ,  ['no' 'yes']
separation_breakdonw_plastics_and_packaging_na  ,  ['no' 'yes']
separation_existence_of_source_separation_na  ,  ['no' 'yes']

In [28]:
cities_df_3['primary_collection_mode_form_of_primary_collection_na'].fillna('not_informed', inplace=True)

In [29]:
cities_df_3['primary_collection_mode_form_of_primary_collection_na'].unique()

array(['Door-to-door collection', 'Centralized drop-off point',
       'not_informed', 'Curbside collection', 'Curbside', 'Multiple',
       'Door-to-door collection: waste collector knocks on door or rings doorbell and waits for resident to bring waste.',
       'Other', 'Door-to-door-collection', 'Block collection',
       'centralized and curbside', 'Door to door collection'],
      dtype=object)

In [30]:
cities_df_3['primary_collection_mode_form_of_primary_collection_na']=cities_df_3['primary_collection_mode_form_of_primary_collection_na'].str.lower()
cities_df_3['primary_collection_mode_form_of_primary_collection_na'].unique()

array(['door-to-door collection', 'centralized drop-off point',
       'not_informed', 'curbside collection', 'curbside', 'multiple',
       'door-to-door collection: waste collector knocks on door or rings doorbell and waits for resident to bring waste.',
       'other', 'door-to-door-collection', 'block collection',
       'centralized and curbside', 'door to door collection'],
      dtype=object)

In [31]:
cities_df_3['primary_collection_mode_form_of_primary_collection_na'].loc[cities_df_3['primary_collection_mode_form_of_primary_collection_na'].str.contains('door')] = 'door to door'
cities_df_3['primary_collection_mode_form_of_primary_collection_na'].unique()

/Users/marike/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:205: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array(['door to door', 'centralized drop-off point', 'not_informed',
       'curbside collection', 'curbside', 'multiple', 'other',
       'block collection', 'centralized and curbside'], dtype=object)

In [32]:
cities_df_3['primary_collection_mode_form_of_primary_collection_na'].loc[cities_df_3['primary_collection_mode_form_of_primary_collection_na'].str.contains('curbside')] = 'curbside'
cities_df_3['primary_collection_mode_form_of_primary_collection_na'].unique()

array(['door to door', 'centralized drop-off point', 'not_informed',
       'curbside', 'multiple', 'other', 'block collection'], dtype=object)

In [33]:
cities_df_3.isna().sum()

country_code                                                                                                       0
region_id                                                                                                          0
income_id                                                                                                          0
city_name                                                                                                          0
composition_food_organic_waste_percent                                                                            76
composition_glass_percent                                                                                         98
composition_metal_percent                                                                                        102
composition_other_percent                                                                                         77
composition_paper_cardboard_percent                                                                               77
composition_plastic_percent                                                                                       84
institutional_framework_department_dedicated_to_solid_waste_management_na                                          0
institutional_framework_information_system_for_solid_waste_management_na                                           0
institutional_framework_unit_enforcing_solid_waste_issues_in_the_city_such_as_illegal_dumping_or_littering_na      0
legal_framework_long_term_integrated_solid_waste_master_plan_na                                                    0
legal_framework_master_plan_is_being_implemented_na                                                                0
legal_framework_solid_waste_management_rules_and_regulations_na                                                    0
population_population_number_of_people                                                                            10
primary_collection_mode_form_of_primary_collection_na                                                              0
separation_breakdonw_cans_and_metals_na                                                                            0
separation_breakdonw_glass_na                                                                                      0
separation_breakdonw_organics_na                                                                                   0
separation_breakdonw_paper_cardboard_na                                                                            0
separation_breakdonw_plastics_and_packaging_na                                                                     0
separation_existence_of_source_separation_na                                                                       0
total_msw_total_msw_generated_tons_year                                                                           41
waste_collection_coverage_total_percent_of_waste_percent_of_waste                                                204
waste_treatment_recycling_percent                                                                                239
dtype: int64

Some columns name are very long and many correspond to subcategories. So for better reading of the information in this notebook, we will modify them using the following expressions:

***compo*** for composition (waste type) percent
    
***IF*** for Institutional Frame work
    
***SW*** for Solid Waste
    
***SW*** for Solid Waste, ***mgmt*** for management
    
***dept*** for department
    
***info*** for information
    
***LF*** for Legal Frame
    
***Separation*** for Separation Breakdown

In [34]:
cities_df_3 = cities_df_3.rename(columns={
'composition_food_organic_waste_percent':'compo_organic', 
'composition_glass_percent':'compo_glass',
'composition_metal_percent':'compo_metal',
'composition_other_percent':'compo_other',
'composition_paper_cardboard_percent':'compo_paper_cardboard',
'composition_plastic_percent':'compo_plastic',
'institutional_framework_department_dedicated_to_solid_waste_management_na':'IF_SW_mgmt_dept',
'institutional_framework_information_system_for_solid_waste_management_na':'IF_SW_mgmt_info',
'institutional_framework_unit_enforcing_solid_waste_issues_in_the_city_such_as_illegal_dumping_or_littering_na':'IF_SW_control_enforcing_unit',
'legal_framework_long_term_integrated_solid_waste_master_plan_na':'LF_long_term_integrated_SW_master_plan',
'legal_framework_master_plan_is_being_implemented_na':'LF_SW_master_plan_being_implemented',
'legal_framework_solid_waste_management_rules_and_regulations_na':'LF_SW_mgmt_rules_and_regulations',
'population_population_number_of_people':'population',
'primary_collection_mode_form_of_primary_collection_na':'primary_collection_form',
'separation_breakdonw_cans_and_metals_na':'separation_metals',
'separation_breakdonw_glass_na':'separation_glass',
'separation_breakdonw_organics_na':'separation_organic',
'separation_breakdonw_paper_cardboard_na':'separation_paper_cardboard',
'separation_breakdonw_plastics_and_packaging_na':'separation_plastics_packaging',
'separation_existence_of_source_separation_na':'separation_existence',
'total_msw_total_msw_generated_tons_year':'MSW_generated_tons_year',
'waste_collection_coverage_total_percent_of_waste_percent_of_waste':'waste_collection_coverage_percent', 
'waste_treatment_recycling_percent':'recycling_percent'
})

We are very interested in recycling information when it is done but since the information is missing for 239 cities of the dataset, we extract the corresponding rows in a specific dataset that we keep to analyse more ahead in the project and we drop this variable from our main dataset.

In [35]:
cities_df_4 = cities_df_3
cities_df_4[['waste_collection_coverage_percent','recycling_percent']]=cities_df_4[['waste_collection_coverage_percent','recycling_percent']].fillna(value=0)
cities_df_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 27 columns):
country_code                              367 non-null object
region_id                                 367 non-null object
income_id                                 367 non-null object
city_name                                 367 non-null object
compo_organic                             291 non-null float64
compo_glass                               269 non-null float64
compo_metal                               265 non-null float64
compo_other                               290 non-null float64
compo_paper_cardboard                     290 non-null float64
compo_plastic                             283 non-null float64
IF_SW_mgmt_dept                           367 non-null object
IF_SW_mgmt_info                           367 non-null object
IF_SW_control_enforcing_unit              367 non-null object
LF_long_term_integrated_SW_master_plan    367 non-null object
LF_SW_master_plan_being_implemented       367 non-null object
LF_SW_mgmt_rules_and_regulations          367 non-null object
population                                357 non-null float64
primary_collection_form                   367 non-null object
separation_metals                         367 non-null object
separation_glass                          367 non-null object
separation_organic                        367 non-null object
separation_paper_cardboard                367 non-null object
separation_plastics_packaging             367 non-null object
separation_existence                      367 non-null object
MSW_generated_tons_year                   326 non-null float64
waste_collection_coverage_percent         367 non-null float64
recycling_percent                         367 non-null float64
dtypes: float64(10), object(17)
memory usage: 77.5+ KB

In [36]:
cities_df_4.loc[cities_df_4.population.isna()]

,country_code,region_id,income_id,city_name,compo_organic,compo_glass,compo_metal,compo_other,compo_paper_cardboard,compo_plastic,...,primary_collection_form,separation_metals,separation_glass,separation_organic,separation_paper_cardboard,separation_plastics_packaging,separation_existence,MSW_generated_tons_year,waste_collection_coverage_percent,recycling_percent
15,ASM,EAS,MiddleUpperIncome,Pago Pago,19.7,3.4,7.9,25.6,26.4,12.8,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.0
60,CMR,SSF,LowMiddleIncome,Limbe,54.8,1.6,2.4,16.3,12.5,12.4,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.0
117,GNQ,SSF,MiddleUpperIncome,Labe,69.0,0.3,1.4,2.0,4.1,22.8,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.0
250,NGA,SSF,LowMiddleIncome,Kano,43.0,2.0,5.0,29.0,17.0,4.0,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.0
292,PSE,MEA,LowMiddleIncome,Ramallah,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.0
353,ZAF,SSF,MiddleUpperIncome,Soweto,9.0,12.0,3.0,64.0,9.0,3.0,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.0
358,ZWE,SSF,LowIncome,Kadoma City,60.0,3.0,3.0,22.0,5.0,7.0,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.0
359,ZWE,SSF,LowIncome,Mbare,28.0,2.0,12.0,25.0,6.0,11.0,...,not_informed,no,no,no,no,no,no,NaN,30.0,0.0
365,ZWE,SSF,LowIncome,Masvingo City,15.0,4.0,5.0,6.0,30.0,40.0,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.0
366,ZWE,SSF,LowIncome,SakubvaÂ,32.0,5.0,6.0,7.0,27.0,23.0,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.0

#### Rows were population number is not informed also correspond to cities where the quantity of generated waste is not indicated. Since the generation of waste is our target variable, we will drop the rows where this information is missing.

In [37]:
cities_df_4.loc[cities_df_4['MSW_generated_tons_year'].isna()]

,country_code,region_id,income_id,city_name,compo_organic,compo_glass,compo_metal,compo_other,compo_paper_cardboard,compo_plastic,...,primary_collection_form,separation_metals,separation_glass,separation_organic,separation_paper_cardboard,separation_plastics_packaging,separation_existence,MSW_generated_tons_year,waste_collection_coverage_percent,recycling_percent
15,ASM,EAS,MiddleUpperIncome,Pago Pago,19.70,3.40,7.90,25.60,26.40,12.80,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
16,AUS,EAS,HighIncome,Perth,40.10,6.80,3.50,22.00,15.20,8.20,...,curbside,yes,yes,yes,yes,yes,no,NaN,0.0,18.00
17,AUS,EAS,HighIncome,Melbourne,68.21,3.00,NaN,1.00,11.44,15.33,...,curbside,no,no,no,no,no,no,NaN,0.0,25.81
36,BGR,ECS,MiddleUpperIncome,Ruse,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
37,BGR,ECS,MiddleUpperIncome,Burgas,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
38,BHR,MEA,HighIncome,Manama,NaN,NaN,NaN,NaN,NaN,NaN,...,curbside,no,no,no,no,no,no,NaN,0.0,0.00
56,CHE,ECS,HighIncome,Zurich,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
60,CMR,SSF,LowMiddleIncome,Limbe,54.80,1.60,2.40,16.30,12.50,12.40,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
69,COM,SSF,LowIncome,Moroni,NaN,NaN,NaN,NaN,NaN,NaN,...,centralized drop-off point,no,no,no,no,no,no,NaN,60.0,0.00
73,CYP,ECS,HighIncome,Paralimini,20.00,5.00,1.00,20.00,11.00,17.00,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
77,DEU,ECS,HighIncome,Hamburg,21.49,4.27,6.53,32.79,25.75,1.60,...,curbside,yes,yes,yes,yes,yes,yes,NaN,0.0,0.00
89,EST,ECS,HighIncome,Tartummaa,0.93,0.02,3.84,74.86,15.06,0.07,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
100,ETH,SSF,LowIncome,Halaba Kulito,88.80,NaN,NaN,5.90,1.70,3.70,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
102,FIN,ECS,HighIncome,Oulu,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,yes,NaN,0.0,0.00
103,FIN,ECS,HighIncome,Riihimaki,48.40,1.60,2.30,17.10,14.20,15.80,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
104,FIN,ECS,HighIncome,Turku,42.80,1.50,1.60,19.90,15.40,17.60,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
112,GEO,ECS,LowMiddleIncome,Tbilisi,69.50,2.40,1.10,4.80,9.50,13.00,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
117,GNQ,SSF,MiddleUpperIncome,Labe,69.00,0.30,1.40,2.00,4.10,22.80,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
128,HUN,ECS,HighIncome,Debrecen,36.95,3.47,3.62,13.54,15.79,15.42,...,curbside,no,yes,yes,yes,yes,yes,NaN,0.0,0.00
131,IMN,ECS,HighIncome,Douglas,NaN,NaN,NaN,NaN,NaN,NaN,...,curbside,no,no,no,no,no,no,NaN,0.0,0.00
182,ISR,MEA,HighIncome,Jerusalem,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,no,NaN,0.0,5.00
183,ISR,MEA,HighIncome,Tel Aviv,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,no,NaN,0.0,10.60
194,KAZ,ECS,MiddleUpperIncome,Kostanay,NaN,NaN,NaN,NaN,NaN,NaN,...,other,no,no,no,no,no,no,NaN,0.0,0.00
195,KEN,SSF,LowMiddleIncome,EldoretÂ,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,no,NaN,45.0,0.00
202,KWT,MEA,HighIncome,Kuwait City,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,no,NaN,100.0,0.00
216,LVA,ECS,HighIncome,Liepaja,26.00,8.00,3.00,37.00,6.00,9.00,...,not_informed,no,yes,no,yes,yes,yes,NaN,0.0,0.00
242,MRT,SSF,LowMiddleIncome,Nouakchott,5.00,4.00,4.00,59.00,7.00,21.00,...,centralized drop-off point,yes,yes,yes,yes,yes,no,NaN,0.0,0.00
248,NGA,SSF,LowMiddleIncome,Ilorin,61.00,NaN,NaN,32.00,7.00,NaN,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
250,NGA,SSF,LowMiddleIncome,Kano,43.00,2.00,5.00,29.00,17.00,4.00,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
256,NLD,ECS,HighIncome,Eindhoven,39.00,3.00,3.00,17.00,19.00,14.00,...,curbside,yes,yes,yes,yes,yes,yes,NaN,0.0,0.00
292,PSE,MEA,LowMiddleIncome,Ramallah,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
300,RWA,SSF,LowIncome,Nyagatare,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,no,NaN,29.0,0.00
330,TUV,EAS,MiddleUpperIncome,Funafuti,52.40,9.50,9.80,8.50,10.40,9.30,...,door to door,no,no,yes,yes,no,no,NaN,0.0,0.00
341,UZB,ECS,LowMiddleIncome,Namangan,NaN,NaN,NaN,NaN,NaN,NaN,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
347,WSM,EAS,MiddleUpperIncome,Upolu (Apia),3.80,2.17,8.83,26.22,7.20,13.04,...,door to door,no,no,yes,no,yes,yes,NaN,90.0,0.00
353,ZAF,SSF,MiddleUpperIncome,Soweto,9.00,12.00,3.00,64.00,9.00,3.00,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
354,ZAF,SSF,MiddleUpperIncome,BloemfonteinÂ,42.60,9.60,4.40,7.50,18.20,17.70,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
358,ZWE,SSF,LowIncome,Kadoma City,60.00,3.00,3.00,22.00,5.00,7.00,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
359,ZWE,SSF,LowIncome,Mbare,28.00,2.00,12.00,25.00,6.00,11.00,...,not_informed,no,no,no,no,no,no,NaN,30.0,0.00
365,ZWE,SSF,LowIncome,Masvingo City,15.00,4.00,5.00,6.00,30.00,40.00,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00
366,ZWE,SSF,LowIncome,SakubvaÂ,32.00,5.00,6.00,7.00,27.00,23.00,...,not_informed,no,no,no,no,no,no,NaN,0.0,0.00

In [38]:
cities_df_5 = cities_df_4.dropna(subset = ['MSW_generated_tons_year'])

In [39]:
cities_df_5.isna().sum()

country_code                               0
region_id                                  0
income_id                                  0
city_name                                  0
compo_organic                             61
compo_glass                               81
compo_metal                               84
compo_other                               62
compo_paper_cardboard                     62
compo_plastic                             68
IF_SW_mgmt_dept                            0
IF_SW_mgmt_info                            0
IF_SW_control_enforcing_unit               0
LF_long_term_integrated_SW_master_plan     0
LF_SW_master_plan_being_implemented        0
LF_SW_mgmt_rules_and_regulations           0
population                                 0
primary_collection_form                    0
separation_metals                          0
separation_glass                           0
separation_organic                         0
separation_paper_cardboard                 0
separation_plastics_packaging              0
separation_existence                       0
MSW_generated_tons_year                    0
waste_collection_coverage_percent          0
recycling_percent                          0
dtype: int64

We create an independent dataset for further study with the information of waste composition when these data are given.

In [40]:
waste_composition = []
for x in cities_df_5.columns:
    if 'compo' in x:
        waste_composition.append(x)
waste_composition

['compo_organic',
 'compo_glass',
 'compo_metal',
 'compo_other',
 'compo_paper_cardboard',
 'compo_plastic']

In [41]:
waste_composition_df = cities_df_5.dropna(subset = waste_composition) 
print(waste_composition_df.shape)
waste_composition_df.info()

(225, 27)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 225 entries, 0 to 364
Data columns (total 27 columns):
country_code                              225 non-null object
region_id                                 225 non-null object
income_id                                 225 non-null object
city_name                                 225 non-null object
compo_organic                             225 non-null float64
compo_glass                               225 non-null float64
compo_metal                               225 non-null float64
compo_other                               225 non-null float64
compo_paper_cardboard                     225 non-null float64
compo_plastic                             225 non-null float64
IF_SW_mgmt_dept                           225 non-null object
IF_SW_mgmt_info                           225 non-null object
IF_SW_control_enforcing_unit              225 non-null object
LF_long_term_integrated_SW_master_plan    225 non-null object
LF_SW_master_plan_being_implemented       225 non-null object
LF_SW_mgmt_rules_and_regulations          225 non-null object
population                                225 non-null float64
primary_collection_form                   225 non-null object
separation_metals                         225 non-null object
separation_glass                          225 non-null object
separation_organic                        225 non-null object
separation_paper_cardboard                225 non-null object
separation_plastics_packaging             225 non-null object
separation_existence                      225 non-null object
MSW_generated_tons_year                   225 non-null float64
waste_collection_coverage_percent         225 non-null float64
recycling_percent                         225 non-null float64
dtypes: float64(10), object(17)
memory usage: 49.2+ KB

**COMPOSITION OF WASTE IN FUNCTION OF GENERATED WASTE & INCOME**

Since we have the waste composition dataset without null information about waste composition, we drop the rows in the recycling dataset where waste composition information is missing.

In [42]:
"""Finally we create one CSV files for further study if requested: 
with complete information regarding cities waste composition (25 variables, 225 cities)."""

waste_composition_df.to_csv('CitiesWasteComposition.csv', index=False)

In [43]:
#finally we create our cities dataset where target variable we are interested in is waste generation, without null information.
cities_df_final = cities_df_5.drop(waste_composition, axis = 1)

In [44]:
cities_df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 326 entries, 0 to 364
Data columns (total 21 columns):
country_code                              326 non-null object
region_id                                 326 non-null object
income_id                                 326 non-null object
city_name                                 326 non-null object
IF_SW_mgmt_dept                           326 non-null object
IF_SW_mgmt_info                           326 non-null object
IF_SW_control_enforcing_unit              326 non-null object
LF_long_term_integrated_SW_master_plan    326 non-null object
LF_SW_master_plan_being_implemented       326 non-null object
LF_SW_mgmt_rules_and_regulations          326 non-null object
population                                326 non-null float64
primary_collection_form                   326 non-null object
separation_metals                         326 non-null object
separation_glass                          326 non-null object
separation_organic                        326 non-null object
separation_paper_cardboard                326 non-null object
separation_plastics_packaging             326 non-null object
separation_existence                      326 non-null object
MSW_generated_tons_year                   326 non-null float64
waste_collection_coverage_percent         326 non-null float64
recycling_percent                         326 non-null float64
dtypes: float64(4), object(17)
memory usage: 56.0+ KB

In [45]:
print('Our final cleaned Cities dataset for the prediction of waste generation has the following shape: ',cities_df_final.shape,'.')

Our final cleaned Cities dataset for the prediction of waste generation has the following shape:  (326, 21) .

#### Finally after exporting our subdatset one with waste composition , we obtain our cleaned final dataset based on 326 cities and 21 variables that we export as CSV file.

In [46]:
cities_df_final.to_csv('CitiesWasteGeneration.csv', index=False)